name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git unzip \
            libffi-dev libssl-dev zlib1g-dev libjpeg-dev libfreetype6-dev liblcms2-dev \
            libncurses5-dev libtinfo5 autoconf automake libtool pkg-config
        python3 -m pip install --upgrade pip setuptools wheel cython buildozer pillow numpy kivy plyer
    
    - name: Install Android SDK using script
      run: |
        wget -q https://raw.githubusercontent.com/kivy/kivy/master/tools/ci/install_android_sdk.sh
        chmod +x install_android_sdk.sh
        ./install_android_sdk.sh
        
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
        echo "PATH=$PATH" >> $GITHUB_ENV
    
    - name: Build APK
      run: |
        export BUILDOZER_ALLOW_ROOT=1
        buildozer -v android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: brutaldoom-apk
        path: bin/*.apk
