name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git openjdk-11-jdk unzip \
              libffi-dev libssl-dev zlib1g-dev libjpeg-dev libfreetype6-dev liblcms2-dev
          python3 -m pip install --upgrade pip setuptools wheel cython buildozer pillow numpy kivy plyer

      - name: Build APK
        run: |
          export BUILDOZER_ALLOW_ROOT=1
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: brutaldoom-apk
          path: bin/*.apk
